pre-push: spdxcheck

diff --git a/bin/pre-push b/bin/pre-push
--- a/bin/pre-push
+++ b/bin/pre-push
@@ -1,4 +1,24 @@
 #!/usr/bin/env bash
+# SPDX-License-Identifier: MIT
+
+# Copyright (c) 2023 Ericsson AB
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy of
+# this software and associated documentation files (the "Software"), to deal in
+# the Software without restriction, including without limitation the rights to
+# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
+# the Software, and to permit persons to whom the Software is furnished to do so,
+# subject to the following conditions:
+
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
+# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
+# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
+# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 set -e
 
@@ -56,6 +76,12 @@ mapfile -t sc_list < <(\
 	cut -d: -f1)
 
 for f in "${sc_list[@]}"; do
+	_echo "spdxcheck: $f"
+	if ! head -2 "${f}" | tail -1 | grep -q '^# SPDX-License-Identifier: MIT$'; then
+		echo "error: '$f': 'SPDX-License-Identifier: MIT' string missing on line 2" 1>&2
+		exit 1
+	fi
+
 	_echo "shebangcheck: $f"
 	if ! head -1 "${f}" | grep -q '#!/usr/bin/env bash'; then
 		echo "error: '$f': wrong shebang" 1>&2
