build-pkg: err on stderr

diff --git a/build-pkg b/build-pkg
--- a/build-pkg
+++ b/build-pkg
@@ -106,7 +106,7 @@ fi
 
 if [ "$o" = "rpm" ]; then
 	if ! command -v alien > /dev/null; then
-		echo "error: command 'alien' missing"
+		echo "error: command 'alien' missing" 1>&2
 		exit 1
 	fi
 	o="gz"
@@ -114,10 +114,10 @@ fi
 
 if [ "$o" = "deb" ]; then
 	if ! command -v dpkg-deb > /dev/null; then
-		echo "error: command 'dpkg-deb' missing"
+		echo "error: command 'dpkg-deb' missing" 1>&2
 		exit 1
 	elif ! command -v fakeroot > /dev/null; then
-		echo "error: command 'fakeroot' missing"
+		echo "error: command 'fakeroot' missing" 1>&2
 		exit 1
 	fi
 	fakeroot \
@@ -138,7 +138,7 @@ elif [ "$o" = "auto" ]; then
 		opt="z"
 		ext="gz"
 	else
-		echo "error: no compression tools (xz, bzip2 nor gzip) found"
+		echo "error: no compression tools (xz, bzip2 nor gzip) found" 1>&2
 		exit 1
 	fi
 else
