deb: use mktemp

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -2,68 +2,68 @@
 
 set -e
 
-version=$(grep ^Version debian/control | cut -d' ' -f2)
-gitdir=$(pwd)
-
-_user=
-if [ "x${USER}" != "x" ]; then
-	_user="${USER}"
-elif [ "x${LOGNAME}" != "x" ]; then
-	_user="${LOGNAME}"
-elif command -v whoami > /dev/null; then
-	_user="$(whoami)"
-else
-	_user="dmce"
+if [ ! -s "debian/control" ]; then
+	echo "error: cd to DMCE base dir"
+	exit 1
+elif ! command -v fakeroot > /dev/null; then
+	echo "error: command 'fakeroot' missing"
+	exit 1
 fi
 
-# Tree structure
-rm -rf /tmp/${_user}/dmce/debian-build
-mkdir -p /tmp/${_user}/dmce/debian-build
+version=$(grep ^Version debian/control | cut -d' ' -f2)
+gitdir=$PWD
 
-cd /tmp/${_user}/dmce/debian-build
-mkdir -p dmce-$version/DEBIAN
-mkdir -p dmce-$version/usr
-mkdir -p dmce-$version/usr/bin
-mkdir -p dmce-$version/usr/share/dmce
+function cleanup {
+	rm -rf "${d:?}"
+}
+trap cleanup EXIT
+
+# tree structure
+d=$(mktemp -d)
+cd "${d}" || exit
+mkdir -p dmce-"${version}"/DEBIAN
+mkdir -p dmce-"${version}"/usr
+mkdir -p dmce-"${version}"/usr/bin
+mkdir -p dmce-"${version}"/usr/share/dmce
 
 # deb files
-cp -a $gitdir/debian/* dmce-$version/DEBIAN
+cp -a "${gitdir}"/debian/* dmce-"${version}"/DEBIAN
 
 # Program files
-cp -a $gitdir/dmce-launcher dmce-$version/usr/bin/
-cp -a $gitdir/dmce-trace dmce-$version/usr/bin/
-cp -a $gitdir/dmce-diff dmce-$version/usr/bin/
-cp -a $gitdir/dmce-trace-viewer dmce-$version/usr/bin/
-cp -a $gitdir/dmce-trace-tgui dmce-$version/usr/bin/
-cp -a $gitdir/dmce-bp-set dmce-$version/usr/bin/
-cp -a $gitdir/dmce-bp-clear dmce-$version/usr/bin/
-cp -a $gitdir/dmce-bp-list dmce-$version/usr/bin/
-cp -a $gitdir/dmce-configure-local dmce-$version/usr/bin/
-cp -a $gitdir/dmce-setup dmce-$version/usr/bin/
-cp -a $gitdir/dmce-set-profile dmce-$version/usr/bin/
-cp -a $gitdir/dmce-summary* dmce-$version/usr/bin/
-cp -a $gitdir/dmce-stats dmce-$version/usr/bin/
-cp -a $gitdir/probe-examples/dmce-probe*   dmce-$version/usr/share/dmce/
-cp -a $gitdir/probe-examples/dmce-prolog*   dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce-post-hook*   dmce-$version/usr/share/dmce/
-cp -a $gitdir/cmdlookuphook.sh dmce-$version/usr/share/dmce/
-cp -a $gitdir/create-clang-diff dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce-copy-headers dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce-remove-relpaths.sh dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.sh dmce-$version/usr/share/dmce/
-cp -a $gitdir/generate-compile-commands.py dmce-$version/usr/share/dmce/
-cp -a $gitdir/generate-probefile.py dmce-$version/usr/share/dmce/
+cp -a "${gitdir}"/dmce-launcher dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-trace dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-diff dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-trace-viewer dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-trace-tgui dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-bp-set dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-bp-clear dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-bp-list dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-configure-local dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-setup dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-set-profile dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-summary* dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/dmce-stats dmce-"${version}"/usr/bin/
+cp -a "${gitdir}"/probe-examples/dmce-probe*   dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/probe-examples/dmce-prolog*   dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce-post-hook*   dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/cmdlookuphook.sh dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/create-clang-diff dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce-copy-headers dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce-remove-relpaths.sh dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.sh dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/generate-compile-commands.py dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/generate-probefile.py dmce-"${version}"/usr/share/dmce/
 
-cp -a $gitdir/constructs.exclude dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.exclude dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.include dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.pos.exclude dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.pos.include dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.var.exclude dmce-$version/usr/share/dmce/
-cp -a $gitdir/dmce.var.include dmce-$version/usr/share/dmce/
-cp -a $gitdir/recognizedexpressions.py dmce-$version/usr/share/dmce/
+cp -a "${gitdir}"/constructs.exclude dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.exclude dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.include dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.pos.exclude dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.pos.include dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.var.exclude dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/dmce.var.include dmce-"${version}"/usr/share/dmce/
+cp -a "${gitdir}"/recognizedexpressions.py dmce-"${version}"/usr/share/dmce/
 
-echo "$version" > dmce-$version/usr/share/dmce/version
+echo "${version}" > dmce-"${version}"/usr/share/dmce/version
 
-fakeroot dpkg-deb --build dmce-${version}
-cp -a /tmp/${_user}/dmce/debian-build/dmce-${version}.deb $gitdir/
+fakeroot dpkg-deb --build dmce-"${version}"
+cp -a dmce-"${version}".deb "${gitdir}"/
