removed hard coded config file path in dmce-summary

diff --git a/dmce-summary b/dmce-summary
--- a/dmce-summary
+++ b/dmce-summary
@@ -19,10 +19,20 @@
 # IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 # CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
-git_root=${PWD##*/}
+git_root=$PWD
+rel_git_root=${PWD##*/}
 
-#TODO: extract config and use from both launcher and summary
-echo "DMCE summary. Using config file: $HOME/.dmceconfig"
+# TODO: Break out read config stuff from summary and launcher
+if [ -e $git_root/.dmceconfig ]; then
+  USE_DMCE_CONFIG_FILE=$git_root/.dmceconfig
+elif [ -e $HOME/.dmceconfig ]; then
+  USE_DMCE_CONFIG_FILE=$HOME/.dmceconfig
+else
+  echo "Could not find a valid dmce config file. Did you run install?"
+  exit 1
+fi
+
+echo "DMCE summary. Using config file: $USE_DMCE_CONFIG_FILE"
 
 while read dmceconfig; do
   validconfig=$(echo $dmceconfig | egrep -v \#)
@@ -32,9 +42,9 @@ while read dmceconfig; do
     eval $conf_var=\'$conf_val\'
     export $conf_var
   fi
-done < $HOME/.dmceconfig
+done < $USE_DMCE_CONFIG_FILE
 
-echo "DMCE probe ref log: $DMCE_WORK_PATH/$git_root/probe-references.log "
+echo "DMCE probe ref log: $DMCE_WORK_PATH/$rel_git_root/probe-references.log "
 echo "Test result log   : $1"
-echo "$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$git_root/probe-references.log"
-$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$git_root/probe-references.log
+echo "$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$rel_git_root/probe-references.log"
+$DMCE_EXEC_PATH/print_summary.py $1 $DMCE_WORK_PATH/$rel_git_root/probe-references.log
