Checkout the new head and bail with a proper message
if the tree is dirty

diff --git a/dmce-launcher b/dmce-launcher
--- a/dmce-launcher
+++ b/dmce-launcher
@@ -108,6 +108,7 @@ offset=0
 number_of_commits=1
 skip=false
 stupid=false
+checkout_head=false
 print_version_and_exit=false
 
 while getopts "$optspec" optchar; do
@@ -120,6 +121,7 @@ while getopts "$optspec" optchar; do
 			head)
 			val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
 			new=$val
+      checkout_head=true
 			;;
 			offset)
 			val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
@@ -129,6 +131,7 @@ while getopts "$optspec" optchar; do
 			val=${OPTARG#*=}
 			opt=${OPTARG%=$val}
 			new=$val
+      checkout_head=true
 			;;
 			offset=*)
 			val=${OPTARG#*=}
@@ -244,6 +247,17 @@ elif [ "$search_method" == "raw" ]; then
   echo "Search from $new to $old"
 else
   usage
+fi
+
+if [ "$checkout_head" = true ]; then
+  git_exit_code=`git checkout $new`
+  if [ "$git_exit_code" != 0 ]; then
+    echo ""
+    echo "Git tree is dirty. Cannot checkout $new."
+    echo "Please clean the $git_root before proceeding."
+    echo ""
+    exit 1
+  fi
 fi
 
 if [ "$skip" = false ]; then
