pre-push: stderr check

diff --git a/.ove/scripts/dmce b/.ove/scripts/dmce
--- a/.ove/scripts/dmce
+++ b/.ove/scripts/dmce
@@ -24,7 +24,7 @@
 # OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 if [ ! -e "${OVE_BASE_DIR:?}/.dmceconfig" ]; then
-    echo "error: '\$OVE_BASE_DIR/.dmceconfig' not found, try to install DMCE by running 'ove install dmce'"
+    echo "error: '\$OVE_BASE_DIR/.dmceconfig' not found, try to install DMCE by running 'ove install dmce'" 1>&2
     exit 1
 fi
 
@@ -124,7 +124,7 @@ function _find {
     fi
 
     if [ ! -e "${prog}" ]; then
-        echo "error: can not find '${1}'"
+        echo "error: can not find '${1}'" 1>&2
         exit 1
     fi
 }
@@ -204,7 +204,7 @@ function main {
             exit 1
         fi
     elif [ "x$(type -t "${1/-/_}")" != "xfunction" ]; then
-        echo "error: '$1' unknown command"
+        echo "error: '$1' unknown command" 1>&2
         exit 1
     else
         if ! ${1/-/_} "$@"; then
diff --git a/.ove/scripts/dmce-coverage-ahead b/.ove/scripts/dmce-coverage-ahead
--- a/.ove/scripts/dmce-coverage-ahead
+++ b/.ove/scripts/dmce-coverage-ahead
@@ -75,11 +75,11 @@ main() {
         usage
         exit 1
     elif [ ! -d "${git_full}" ]; then
-        echo "error: ${git_full} is not a directory"
+        echo "error: ${git_full} is not a directory" 1>&2
         usage
         exit 1
     elif [ ! -d "${git_full}"/.git ]; then
-        echo "error: ${git_full} does not appear to be a git repo"
+        echo "error: ${git_full} does not appear to be a git repo" 1>&2
         usage
         exit 1
     fi
@@ -92,10 +92,10 @@ main() {
     mapfile -t revs <<<"$(ove-ahead "$git" | \grep -o '^[a-f0-9]\+')"
     nbr_revs=${#revs[@]}
     if [ "${nbr_revs}" -eq 0 ]; then
-        echo "error: no revs"
+        echo "error: no revs" 1>&2
         exit 1
     elif [ "${nbr_revs}" -eq 1 ] && [ "x${revs[0]}" = "x" ]; then
-        echo "error: no revs"
+        echo "error: no revs" 1>&2
         exit 1
     fi
 
@@ -109,7 +109,7 @@ main() {
     # sanity check
     for i in $(seq 0 $((nbr_revs - 1))); do
         if ! git -C "$git_full" cat-file -e "${revs[i]}" &> /dev/null; then
-            echo "error: '${revs[i]}' is not a valid rev"
+            echo "error: '${revs[i]}' is not a valid rev" 1>&2
             exit 1
         fi
     done
diff --git a/.ove/scripts/dmce-coverage-history b/.ove/scripts/dmce-coverage-history
--- a/.ove/scripts/dmce-coverage-history
+++ b/.ove/scripts/dmce-coverage-history
@@ -244,11 +244,11 @@ function init() {
         usage
         exit 1
     elif [ ! -d "${git_full}" ]; then
-        echo "error: ${git_full} is not a directory"
+        echo "error: ${git_full} is not a directory" 1>&2
         usage
         exit 1
     elif [ ! -d "${git_full}"/.git ]; then
-        echo "error: ${git_full} does not appear to be a git repo"
+        echo "error: ${git_full} does not appear to be a git repo" 1>&2
         usage
         exit 1
     fi
@@ -271,7 +271,7 @@ function init() {
         mode="$1"
         shift
         if [[ ! "${mode}" =~ ^[1-7]$ ]]; then
-            echo "error: unknown mode: '$mode'"
+            echo "error: unknown mode: '$mode'" 1>&2
 
             #usage
             exit 1
@@ -299,17 +299,17 @@ function init() {
 
     nbr_revs=${#revs[@]}
     if [ "${nbr_revs}" -eq 0 ]; then
-        echo "error: no revs"
+        echo "error: no revs" 1>&2
         exit 1
     elif [ "${nbr_revs}" -eq 1 ]; then
-        echo "error: provide at least two revisions"
+        echo "error: provide at least two revisions" 1>&2
         exit 1
     fi
 
     # sanity check
     for i in $(seq 0 $((nbr_revs - 1))); do
         if ! git -C "${git_full}" cat-file -e "${revs[i]}" &> /dev/null; then
-            echo "error: '${revs[i]}' is not a valid rev"
+            echo "error: '${revs[i]}' is not a valid rev" 1>&2
             exit 1
         fi
 
@@ -329,40 +329,40 @@ function init() {
     ove-worktree remove "$worktree" || true
     ove-echo cyan "ove-worktree add ${worktree}"
     if ! ove-worktree add "$worktree"; then
-        echo "error: 'ove-worktree add ${worktree}' failed"
+        echo "error: 'ove-worktree add ${worktree}' failed" 1>&2
         exit 1
     fi
 
     if ! cd "${worktree}"; then
-        echo "error: 'cd ${worktree}' failed, weird!"
+        echo "error: 'cd ${worktree}' failed, weird!" 1>&2
         exit 1
     fi
 
     # shellcheck disable=SC1091
     source ove
     if ! ove buildme dmce; then
-        echo "error: 'ove buildme dmce' failed, weird!"
+        echo "error: 'ove buildme dmce' failed, weird!" 1>&2
         exit 1
     fi
 
     if ! cd "${worktree}/${git}"; then
-        echo "error: 'cd ${worktree}/${git}' failed, weird!"
+        echo "error: 'cd ${worktree}/${git}' failed, weird!" 1>&2
         exit 1
     fi
 
     if ! ove dmce launch -c -- "$git"; then
-        echo "error: 'ove-dmce launch -c -- $git' failed"
+        echo "error: 'ove-dmce launch -c -- $git' failed" 1>&2
         exit 1
     fi
 
     ove-echo cyan "ove-dmce set-profile syslog"
     if ! ove dmce set-profile syslog; then
-        echo "error: 'ove-dmce set-profile syslog' failed"
+        echo "error: 'ove-dmce set-profile syslog' failed" 1>&2
         exit 1
     fi
 
     if ! command -v journalctl > /dev/null; then
-        echo "error: command 'journalctl' is missing"
+        echo "error: command 'journalctl' is missing" 1>&2
         exit 1
     fi
 
diff --git a/.ove/scripts/dmce-trace-decode b/.ove/scripts/dmce-trace-decode
--- a/.ove/scripts/dmce-trace-decode
+++ b/.ove/scripts/dmce-trace-decode
@@ -89,7 +89,7 @@ function main() {
 	proj="$1"
 
 	if [ ! -d "/tmp/$OVE_USER/dmce" ]; then
-		echo "error: no '/tmp/$OVE_USER/dmce' directory"
+		echo "error: no '/tmp/$OVE_USER/dmce' directory" 1>&2
 		usage
 		exit 1
 	fi
@@ -98,7 +98,7 @@ function main() {
 		grep "[0-9]$" | \
 		LC_ALL=C sort > "/tmp/$OVE_USER/dmce/dmce-trace-prepare.post"
 	if [ ! -s "/tmp/$OVE_USER/dmce/dmce-trace-prepare.post" ]; then
-		echo "error: no dmcebuffer files found"
+		echo "error: no dmcebuffer files found" 1>&2
 		usage
 		exit 1
 	fi
@@ -119,7 +119,7 @@ function main() {
 	# go through each trace
 	for b in $b_list; do
 		if [ ! -s "$b.info" ]; then
-			echo "error: no '$b.info' file"
+			echo "error: no '$b.info' file" 1>&2
 			continue
 		fi
 
diff --git a/.ove/scripts/dmce-trace-lazy b/.ove/scripts/dmce-trace-lazy
--- a/.ove/scripts/dmce-trace-lazy
+++ b/.ove/scripts/dmce-trace-lazy
@@ -53,7 +53,7 @@ function init() {
 	if ! path=$(ove-proj2val "${proj}" path); then
 		exit 1
 	elif ! repo=$(git -C "${path}" rev-parse --show-toplevel 2> /dev/null); then
-		echo "error: can not get git toplevel for '${path}'"
+		echo "error: can not get git toplevel for '${path}'" 1>&2
 		exit 1
 	fi
 
@@ -63,7 +63,7 @@ function init() {
 
 function instrument() {
 	if ! ove dmce-trace-prepare-auto "${proj}"; then
-		echo "error: 'ove dmce-trace-prepare-auto ${proj}' failed"
+		echo "error: 'ove dmce-trace-prepare-auto ${proj}' failed" 1>&2
 		exit 1
 	fi
 }
@@ -142,7 +142,7 @@ function execute() {
 		i=$((i + 1))
 	done
 	if [ "${i}" -eq 0 ]; then
-		echo "error: no executables found"
+		echo "error: no executables found" 1>&2
 		exit 1
 	fi
 
diff --git a/.ove/scripts/dmce-trace-prepare b/.ove/scripts/dmce-trace-prepare
--- a/.ove/scripts/dmce-trace-prepare
+++ b/.ove/scripts/dmce-trace-prepare
@@ -166,7 +166,7 @@ function main() {
 				n=$(git -C "$repo" grep 'DMCE_NBR_OF_PROBES ('| cut -d: -f2 | sort -u | wc -l)
 				# assert
 				if [ "$n" -ne 1 ]; then
-					echo "error: more than one DMCE_NBR_OF_PROBES in '${repo_short}'"
+					echo "error: more than one DMCE_NBR_OF_PROBES in '${repo_short}'" 1>&2
 					exit 1
 				fi
 
@@ -302,7 +302,7 @@ function dmce_one_repo {
 				profiles="$(dmce-set-profile -l)"
 				re=\\b$profile\\b
 				if [[ ! "${profiles}" =~ ${re} ]]; then
-					echo "error: wrong profile '$profile' - available: $profiles"
+					echo "error: wrong profile '$profile' - available: $profiles" 1>&2
 					return 1
 				fi
 			fi
diff --git a/.ove/scripts/dmce-trace-prepare-auto b/.ove/scripts/dmce-trace-prepare-auto
--- a/.ove/scripts/dmce-trace-prepare-auto
+++ b/.ove/scripts/dmce-trace-prepare-auto
@@ -134,7 +134,7 @@ function sanity_checks() {
 		usage
 		exit 1
 	elif [ ! -e "${OVE_BASE_DIR:?}/.config/dmce/constructs.exclude" ]; then
-		echo "error: run 'ove install dmce' and try again"
+		echo "error: run 'ove install dmce' and try again" 1>&2
 		exit 1
 	elif [ ! -s "${profile_db}" ]; then
 		echo "creating '${profile_db}'"
@@ -148,11 +148,11 @@ function sanity_checks() {
 		# first save previous entry then update it with '-e foo.c'
 		if ! sed -i -e "s,^\($1:trace:.*trace-mc\),#\1\n\1,g" \
 			"${profile_db}"; then
-			echo "error: could not save previous entry in '${profile_db}'"
+			echo "error: could not save previous entry in '${profile_db}'" 1>&2
 			exit 1
 		elif ! sed -i -e "s,^\($1:trace:.*\) trace-mc,\1 -e foo.c trace-mc,g" \
 			"${profile_db}"; then
-			echo "error: failed to update '${profile_db}'"
+			echo "error: failed to update '${profile_db}'" 1>&2
 			exit 1
 		fi
 	fi
diff --git a/bin/dmce-trace-viewer b/bin/dmce-trace-viewer
--- a/bin/dmce-trace-viewer
+++ b/bin/dmce-trace-viewer
@@ -82,7 +82,7 @@ function init() {
 
 # TODO: remove or check comma-separated list
 #    if [ ! -d "${git_full}" ]; then
-#        echo "error: ${git_full} is not a directory"
+#        echo "error: ${git_full} is not a directory" 1>&2
 #        usage
 #    fi
 }
@@ -118,13 +118,13 @@ function main() {
     dmce_trace_args+=" ${git_full}"
 
     if ! eval dmce-trace "${dmce_trace_args}" > "${dmce_trace_log:?}"; then
-        echo "error: 'dmce-trace ${dmce_trace_args}' failed"
+        echo "error: 'dmce-trace ${dmce_trace_args}' failed" 1>&2
         exit 1
     fi
 
     # sanity check
     if [ ! -s "${dmce_trace_log:?}" ]; then
-        echo "error: dmce-trace was successful but we got no output"
+        echo "error: dmce-trace was successful but we got no output" 1>&2
         exit 1
     fi
     files+=" ${dmce_trace_log}"
@@ -132,7 +132,7 @@ function main() {
     # TODO: Remove or make work with comma-separated list
 #    echo "$ cd ${git_full}"
 #    if ! cd "${git_full}"; then
-#        echo "error: 'cd ${git_full}' failed, weird!"
+#        echo "error: 'cd ${git_full}' failed, weird!" 1>&2
 #        exit 1
 #    fi
 
diff --git a/bin/pre-push b/bin/pre-push
--- a/bin/pre-push
+++ b/bin/pre-push
@@ -3,6 +3,7 @@
 set -e
 
 if [ ! -d .git ]; then
+	echo "error: run from git root" 1>&2
 	exit 1
 elif ! command -v shellcheck > /dev/null; then
 	echo "error: command 'shellcheck' missing" 1>&2
@@ -16,21 +17,32 @@ mapfile -t sc_list < <(\
 	grep 'Bourne-Again shell script' | \
 	cut -d: -f1)
 
+function _echo() {
+	if command -v figlet > /dev/null; then
+		figlet -t "$*"
+	else
+		echo "$*"
+	fi
+}
+
 for f in "${sc_list[@]}"; do
-	# check shebang
+	_echo "shebangcheck: $f"
 	if ! head -1 "${f}" | grep -q '#!/usr/bin/env bash'; then
 		echo "error: '$f': wrong shebang" 1>&2
 		exit 1
 	fi
 
-	# pretty print
-	if command -v figlet > /dev/null; then
-		figlet -t "shellcheck: $f"
-	else
-		echo "shellcheck: $f"
+	# ignore self
+	if [ "$f" != "bin/pre-push" ]; then
+		_echo "stderrcheck: $f"
+		if grep 'echo "error:' "${f}" | grep -q -v '1>&2$'; then
+			echo "error: '$f': redirect errors to stderr" 1>&2
+			grep -H -n 'echo "error:' "${f}" | grep -v '1>&2$'
+			exit 1
+		fi
 	fi
 
-	# run shellcheck
+	_echo "shellcheck: $f"
 	if ! shellcheck "$f"; then
 		exit 1
 	fi
