ove: dmce: reworked

diff --git a/.ove/scripts/dmce b/.ove/scripts/dmce
--- a/.ove/scripts/dmce
+++ b/.ove/scripts/dmce
@@ -1,133 +1,213 @@
 #!/usr/bin/env bash
+# SPDX-License-Identifier: MIT
+#
+# MIT License
+#
+# Copyright (c) 2020-2021 Ericsson
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is furnished
+# to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice (including the next
+# paragraph) shall be included in all copies or substantial portions of the
+# Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
+# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
+# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
+# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
-if ! cd "${OVE_BASE_DIR:?}"; then
-	echo "error: 'cd ${OVE_BASE_DIR}' failed"
+if [ ! -e "${OVE_BASE_DIR:?}/.dmceconfig" ]; then
+	echo "error: '\$OVE_BASE_DIR/.dmceconfig' not found, try to install DMCE by running 'ove install dmce'"
 	exit 1
 fi
 
-dmce_launcher="${OVE_ACTIVE_REPO_DIR:?}/dmce-launcher"
-if [ ! -e "$dmce_launcher" ]; then
-	echo "error: can not find DMCE launcher"
-	exit 1
-fi
+default_args="-f ${OVE_BASE_DIR:?}/.dmceconfig"
 
-try_to_identify_repo=0
-if [ $# -eq 0 ]; then
-	repos="$OVE_REPO_LIST"
-	try_to_identify_repo=1
-else
-	while true; do
-		[ "x$*" = "x" ] && break
+function usage {
+        cat << EOF
+NAME
+        OVE plugin for DMCE
 
-		# sanity check
-		if ! [ -d "$1" ] || \
-			! [ -d "$1/.git" ]; then
-			shift
+SYNOPSIS
+        ove dmce <command> [options] [-- git...]
+
+DESCRIPTION
+        Use DMCE within a OVE workspace
+
+LOW-LEVEL COMMANDS
+        set-profile:
+          # select DMCE profile
+          $ ove dmce set-profile [options]
+
+        launch:
+          # run 'dmce-launcher' in sequence on all/specified repos
+          $ ove dmce launch [options] [-- git...]
+
+        summary-bin:
+          # run 'dmce-summary-bin'
+          $ ove dmce summary-bin [options]
+
+        summary-txt:
+          # run 'dmce-summary-txt'
+          $ ove dmce summary-txt [options]
+
+        trace:
+          # run 'dmce-trace'
+          $ ove dmce trace [options]
+
+HIGH-LEVEL COMMANDS
+EOF
+	for f in "${OVE_ACTIVE_REPO_DIR}"/.ove/scripts/dmce-*; do
+		g=${f##*/}
+		if [[ $g == *.* ]]; then
 			continue
 		fi
-		repos+="$(readlink -f "$1") "
-		shift
+		g=${g/dmce-}
+
+		echo "        $g:"
+		echo "          # run 'ove dmce $g' for detailed description"
+		echo
 	done
-
-fi
-
-if [ "x${repos}" = "x" ]; then
-	echo "error: no git repos found, try again"
-	exit 1
-fi
-
-
-git_dir=$(git -C "${BASH_SOURCE[0]%/*}" rev-parse --show-toplevel)
-if ! git_dir=$(cd "${git_dir}" || exit; pwd -P); then
-	echo "error: 'cd ${git_dir}' failed"
-	exit 1
-fi
-
-# $1: dir
-# returns 0 if one or more c/c++ file (based on file extension)
-function determine_if_repo_is_dmceable {
-	nbr_of_files=$(find "$1" -xdev -type f -name '*.c' -or -name '*.cpp' -or -name '*.cc' 2> /dev/null | wc -l)
-	if [ "${nbr_of_files}" -gt 0 ]; then
-		return 0
+	echo "FILES"
+	echo "        \$OVE_BASE_DIR/.dmceconfig"
+	if [ -d "${OVE_BASE_DIR}"/.config/dmce ]; then
+		find "${OVE_BASE_DIR}"/.config/dmce | sed -e "s,$OVE_BASE_DIR,\$OVE_BASE_DIR," -e 's,^,        ,g'
 	else
-		return 1
+		echo "  ${OVE_BASE_DIR}/.config/dmce/*"
+	fi
+	echo
+	cat << EOF
+EXAMPLES
+        # set 'trace' profile
+        $ ove dmce set-profile trace
+
+        # launch DMCE on two repos
+        $ ove dmce launch -a -q -- ag dmce-examples
+
+        # trace, build, run, view in one go
+        $ ove dmce trace-prepare ag ag && { ag foobar; ove dmce trace-decode ag; }
+EOF
+}
+
+function _getopts {
+	local args
+
+	args="$*"
+	if [[ ${args} = *--[[:space:]]* ]]; then
+		opts=${args%%-- *}
+		repos=${args##*--}
+		repos="${repos//${OVE_BASE_DIR}\//}"
+	else
+		opts=${args}
+		repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
 	fi
 }
 
-_repos=()
-for repo in $repos; do
-	# skip DMCE repo
-	[ "${repo}" == "${git_dir}" ] && continue
-
-	# skip repos without C or C++ files
-	if [ ${try_to_identify_repo} -eq 1 ] && ! determine_if_repo_is_dmceable "${repo}"; then
-		continue
+# $1: prog
+function _find {
+	# try to find binary
+	if ! command -v "${1}" > /dev/null; then
+		prog="${OVE_ACTIVE_REPO_DIR:?}/${1}"
+	else
+		prog="$(command -v "${1}")"
 	fi
 
-	_repos+=("${repo}")
-done
-
-if [ "${#_repos[@]}" -eq 0 ]; then
-	echo "error: no git repos found, try again"
-	exit 1
-elif [ "${#_repos[@]}" -ne 1 ]; then
-	echo "about to launch DMCE on ${#_repos[@]} repos: $(printf "%s " "${_repos[@]}")" | \
-		sed -e "s,$OVE_BASE_DIR/,,g"
-fi
-
-default_n=0
-timeout=3
-if [ -t 1 ]; then
-	while true; do
-		read -r -t ${timeout} -p "#commits to probe? (0 = entire git history on current branch) "
-		ret=$?
-		if [ $ret -gt 128 ]; then
-			n=${default_n}
-			echo
-			break
-		elif [ $ret -eq 0 ] && [ "x${REPLY}" = "x" ]; then
-			continue
-		elif ! [[ "${REPLY}" =~ ^[0-9]+$ ]]; then
-			echo "error: just numbers, try again!"
-			continue
-		else
-			n=${REPLY}
-			break
-		fi
-	done
-else
-	n=${default_n}
-fi
-
-run() {
-	local cmd
-
-	cmd="$*"
-	echo "$ $cmd"
-	if ! $cmd; then
-		echo "error: '$cmd' failed"
-		return 1
-	fi
-}
-
-# set syslog profile
-if ! run "${OVE_ACTIVE_REPO_DIR:?}/dmce-set-profile -s -d ${OVE_ACTIVE_REPO_DIR} -p syslog"; then
-	exit 1
-fi
-
-if [ $n -eq 0 ]; then
-	args="-a"
-else
-	args="-n ${n}"
-fi
-
-# run 'dmce-launcher' on all repos
-for repo in "${_repos[@]}"; do
-	if ! run "cd ${repo}"; then
+	if [ ! -e "${prog}" ]; then
+		echo "error: can not find '${1}'"
 		exit 1
-	elif ! run "${dmce_launcher} -c -q"; then
-		continue
-	elif ! run "${dmce_launcher} $args -q"; then
-		continue
 	fi
-done
+}
+
+function run {
+	echo "$ ${prog} ${opts}" 1>&2
+	eval "${prog}" "${opts}"
+}
+
+function set_profile {
+	local args
+
+	shift
+	_find "dmce-set-profile"
+	_getopts "$@"
+	opts="$default_args -p -d $OVE_BASE_DIR/.config/dmce $opts"
+	run
+}
+
+function launch {
+	local opts
+	local r
+	local repos
+
+	shift
+
+	_find "dmce-launcher"
+	if [ $# -eq 0 ]; then
+		opts="-a -q"
+		repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+	else
+		_getopts "$@"
+	fi
+
+	opts="$default_args $opts"
+	for r in $repos; do
+		[ -d "$OVE_BASE_DIR"/"$r" ] || continue
+		cd "$OVE_BASE_DIR/$r" || continue
+		if [ "x$PWD" = "x${OVE_ACTIVE_REPO_DIR}" ]; then
+			continue
+		fi
+		run
+	done
+}
+
+function trace {
+	shift
+	_find "dmce-trace"
+	_getopts "$@"
+	run
+}
+
+function summary_bin {
+	shift
+	_find "dmce-summary-bin"
+	_getopts "$@"
+	run
+}
+
+function summary_txt {
+	shift
+	_find "dmce-summary-txt"
+	_getopts "$@"
+	run
+}
+
+function main {
+	if [ $# -eq 0 ]; then
+		usage
+		exit 1
+	fi
+
+	cmd=$1
+	n="${OVE_ACTIVE_REPO_DIR}/.ove/scripts/dmce-${cmd/_/-}"
+	if [ -s "${n}" ]; then
+		shift
+		if ! "${n}" "$@"; then
+			exit 1
+		fi
+	elif [ "x$(type -t "${1/-/_}")" != "xfunction" ]; then
+		echo "error: '$1' unknown command"
+		exit 1
+	else
+		if ! ${1/-/_} "$@"; then
+			exit 1
+		fi
+	fi
+}
+
+main "$@"
diff --git a/.ove/scripts/dmce-trace-decode b/.ove/scripts/dmce-trace-decode
--- a/.ove/scripts/dmce-trace-decode
+++ b/.ove/scripts/dmce-trace-decode
@@ -1,4 +1,27 @@
 #!/usr/bin/env bash
+# SPDX-License-Identifier: MIT
+#
+# MIT License
+#
+# Copyright (c) 2021 Ericsson
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is furnished
+# to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice (including the next
+# paragraph) shall be included in all copies or substantial portions of the
+# Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
+# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
+# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
+# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 function usage() {
 	local repos
@@ -6,10 +29,43 @@ function usage() {
 	repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
 	repos="${repos/dmce/}"
 	repos="${repos/  / }"
-	echo "usage:"
-	echo "  $(basename $0) git"
-	echo
-	echo "choose from: $repos"
+	cat << EOF
+NAME
+        Decode DMCE trace buffer
+
+SYNOPSIS
+        ove dmce trace-decode git
+
+OPTIONS
+        git:
+          choose one git of: ${repos}
+
+PREREQUISITE
+	A successful run of 'ove dmce trace-prepare'
+
+DESCRIPTION
+        This OVE plugin will decode one DMCE trace buffer and display the raw trace to the user.
+        If 'fzf' (=github.com/junegunn/fzf) is installed an interactive viewer is launched.
+
+        It's possible to force the viewer to 'fzf', 'less', 'stdout', 'stderr' or '<file>'. See EXAMPLES below!
+
+CONFIGURATION
+        # select trace viewer tool
+        DMCE_TRACE_VIEWER stdout|stderr|less|fzf|<file>
+
+EXAMPLES
+        # install fzf
+        $ <package manager> install fzf
+
+        # decode the trace buffer and launch an interactive fzf viewer
+        $ ove dmce trace-decode ag
+
+        # decode the trace buffer and display the trace on stdout
+        $ DMCE_TRACE_VIEWER=stdout ove dmce trace-decode ag
+
+        # decode the trace buffer and save the trace to a file '/tmp/a.trace'
+        $ DMCE_TRACE_VIEWER=/tmp/a.trace ove dmce trace-decode ag
+EOF
 	exit 1
 }
 
@@ -106,19 +162,34 @@ function main() {
 	dmce_trace_args+=" --format raw"
 	dmce_trace_args+=" --numvars 5"
 	dmce_trace_args+=" -t"
-	dmce_trace_args+=" /tmp/dmcebuffer.bin"
+	dmce_trace_args+=" /tmp/$OVE_USER/dmce/dmcebuffer.bin"
 	dmce_trace_args+=" /tmp/$OVE_USER/dmce/${git_base}/probe-references.log"
 	dmce_trace_args+=" ${git_full}"
-	if ! command -v fzf > /dev/null; then
-		fzf=0
-		dmce_trace_args+=" --hl"
+
+	fzf=0
+	# not set, select fzf if it's available
+	if [ "x$DMCE_TRACE_VIEWER" = "x" ]; then
+		if ! command -v fzf > /dev/null; then
+			fzf=0
+			dmce_trace_args+=" --hl"
+		else
+			fzf=1
+		fi
+	elif [ "x$DMCE_TRACE_VIEWER" = "xfzf" ]; then
+		# fzf is forced but not available, fallback to 'less'
+		if ! command -v fzf > /dev/null; then
+			fzf=0
+		else
+			fzf=1
+		fi
 	else
-		fzf=1
+		# fzf is 0, select less/stdout/stderr/file below
+		:
 	fi
 
-	echo "$ dmce-trace ${dmce_trace_args}"
-	if ! "${OVE_ACTIVE_REPO_DIR:?}"/dmce-trace ${dmce_trace_args} > ${dmce_trace_log}; then
-		echo "error: dmce-trace failed"
+	echo "$ ove-dmce-trace ${dmce_trace_args}"
+	if ! ove-dmce trace ${dmce_trace_args} > ${dmce_trace_log}; then
+		echo "error: 'ove-dmce-trace ${dmce_trace_args}' failed"
 		exit 1
 	fi
 
@@ -184,10 +255,21 @@ function main() {
 	if [ -s "${dmce_trace_diff}" ]; then
 		git apply "${dmce_trace_diff}" 2> /dev/null
 	fi
-
 	# none-fzf: simply display the log
 	if [ $fzf -eq 0 ]; then
-		column -t -s'@' ${dmce_trace_log}
+		if [ "x$DMCE_TRACE_VIEWER" = "x" ] || [ "x$DMCE_TRACE_VIEWER" = "xstdout" ]; then
+			column -t -s'@' ${dmce_trace_log}
+		elif [ "x$DMCE_TRACE_VIEWER" = "xless" ]; then
+			column -t -s'@' ${dmce_trace_log} | less -r
+		elif [ "x$DMCE_TRACE_VIEWER" = "xstderr" ]; then
+			column -t -s'@' ${dmce_trace_log} 1>&2
+		else
+			echo "saving trace as '$(readlink -f $DMCE_TRACE_VIEWER)'"
+			if ! column -t -s'@' ${dmce_trace_log} > $DMCE_TRACE_VIEWER; then
+				exit 1
+			fi
+		fi
+
 		exit 0
 	fi
 
diff --git a/.ove/scripts/dmce-trace-prepare b/.ove/scripts/dmce-trace-prepare
--- a/.ove/scripts/dmce-trace-prepare
+++ b/.ove/scripts/dmce-trace-prepare
@@ -1,24 +1,71 @@
 #!/usr/bin/env bash
+# SPDX-License-Identifier: MIT
+#
+# MIT License
+#
+# Copyright (c) 2021 Ericsson
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is furnished
+# to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice (including the next
+# paragraph) shall be included in all copies or substantial portions of the
+# Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
+# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
+# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
+# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
+# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 function usage() {
 	local projs
 	local repos
 
 	repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	repos="${repos/dmce/}"
 	repos="${repos/  / }"
-	projs="${OVE_PROJECT_LIST/dmce/}"
-	projs="${projs/  / }"
-	echo "usage:"
-	echo "  $(basename $0) git proj"
-	echo
-	echo "git:"
-	echo "  choose one from: ${repos}"
-	echo
-	echo "proj:"
-	echo "  choose one from: ${projs}"
+	projs="${OVE_PROJECT_LIST}"
+	cat << EOF
+NAME
+        Insert DMCE probes into one repo and build it
 
-	exit 1
+SYNOPSIS
+        ove dmce trace-prepare git proj
+
+OPTIONS
+        git:
+          choose one git of: ${repos}
+
+        proj:
+          choose one from: ${projs}
+
+DESCRIPTION
+        This plugin is a helper that will insert probes into one git repo. As OVE
+        know how to build the project 'proj' this plugin will also build the code.
+
+        Use 'ove dmce trace-decode' to decode the trace buffer. Don't forget to install 'fzf'!
+
+EXAMPLES
+        # install fzf
+        $ <package manager> install fzf
+
+        # prepare the git and build it
+        $ ove dmce trace-prepare ag ag
+
+        # run some test, here we're searching for the word 'foobar'
+        $ ag foobar
+
+        # decode the trace buffer and launch an interactive fzf viewer
+        $ ove dmce trace-decode ag
+
+        # oneliner (all of the above in one go)
+        $ ove dmce trace-prepare ag ag && { ag foobar; ove dmce trace-decode ag; }
+EOF
 }
 
 function main() {
@@ -29,27 +76,18 @@ function main() {
 	# usage and sanity checks
 	if [ $# -lt 2 ]; then
 		usage
+		exit 1
 	elif [ ! -d "${git_full}" ]; then
 		echo "error: ${git_full} is not a directory"
 		usage
+		exit 1
 	elif [ ! -d "${git_full}"/.git ]; then
 		echo "error: ${git_full} does not appear to be a git repo"
 		usage
+		exit 1
 	fi
 
 	name="$(basename "$0")-${git/\//_}"
-
-	if [ "x${DMCE_TRACE_AUTOMATION}" = "x" ]; then
-		echo "WARNING: this script will do a HARD reset (=git reset -q --hard) AND clean up (=git clean -dfxq) this repo: ${git_full}"
-		read -p "continue? (y/N) " -r
-		if ! [[ "${REPLY}" =~ ^[Yy]$ ]]; then
-			exit 1
-		fi
-		read -p "are you REALLY sure? (y/N) " -r
-		if ! [[ ${REPLY} =~ ^[Yy]$ ]]; then
-			exit 1
-		fi
-	fi
 
 	echo "$ cd ${git_full}"
 	if ! cd "${git_full}"; then
@@ -60,7 +98,8 @@ function main() {
 	launch=1
 	stash=$(git stash list | grep 'dmce')
 	if [ "x${DMCE_TRACE_AUTOMATION}" = "x" ] && [ "x${stash}" != "x" ]; then
-		read -t 3 -p "use stashed instrumentation (this dialog will timeout in 3 seconds)? (y/N) " -r
+		printf "%s\n" "$stash"
+		read -t 10 -p "use stashed instrumentation (this dialog will timeout in 10 seconds)? (y/N) " -r
 		ret=$?
 		if [ ${ret} -gt 128 ]; then
 			echo
@@ -90,19 +129,32 @@ function main() {
 	fi
 
 	if [ ${launch} -eq 1 ]; then
-		echo "$ dmce-set-profile -d ${OVE_ACTIVE_REPO_DIR} -p trace"
-		if ! "${OVE_ACTIVE_REPO_DIR}/dmce-set-profile" -d "${OVE_ACTIVE_REPO_DIR}" -p trace; then
-			echo "error: 'dmce-set-profile -p trace' failed"
+		echo "$ ove-dmce set-profile trace"
+		if ! ove-dmce set-profile trace; then
+			echo "error: 'ove dmce set-profile trace' failed"
 			exit 1
 		fi
 
-		echo "$ git -C ${git_full} clean -dfxq"
-		if ! git -C "${git_full}" clean -dfxq; then
-			ove_echo_red_noprefix "error: 'git clean -dfxq' failed"
-			exit 1
-		elif git -C ${git_full} grep -q 'DMCE_PROBE('; then
-			ove_echo_red_noprefix "error: the git is full of probes. Cleanup!"
-			exit 1
+		if git -C "${git_full}" grep -q 'DMCE_PROBE('; then
+			if [ "x${DMCE_TRACE_AUTOMATION}" != "x" ] && [ "${DMCE_TRACE_AUTOMATION}" -eq 1 ]; then
+				# do nothing
+				true
+			else
+				read -r -p "info: repo '${git}' is already probed! git stash && git stash drop? (y/N)"
+				if ! [[ ${REPLY} =~ ^[Yy]$ ]]; then
+					exit 1
+				fi
+			fi
+
+			if ! git -C "${git_full}" stash -q; then
+				ove_echo_red_noprefix "error: 'git -C ${git_full} stash' failed"
+				exit 1
+			fi
+
+			if ! git -C "${git_full}" stash drop -q; then
+				ove_echo_red_noprefix "error: 'git -C ${git_full} stash drop' failed"
+				exit 1
+			fi
 		fi
 
 		# save any local modifications
@@ -114,14 +166,14 @@ function main() {
 			rm "${dmce_trace_diff}"
 		fi
 
-		echo "$ dmce-launcher -a"
-		out=$("${OVE_ACTIVE_REPO_DIR:?}"/dmce-launcher -a)
+		echo "$ ove-dmce launch -a -- $git_full"
+		out=$(ove-dmce launch -a -- "$git_full")
 		ret=$?
 		if [ ${ret} -ne 0 ]; then
 			if [[ ${out} == *error* ]]; then
 				err_string="$(echo "${out}"| grep error: | sed 's,error: ,,g')"
 			else
-				err_string="'dmce-launcher -a' failed"
+				err_string="'ove-dmce launch -a -- $git_full' failed"
 			fi
 			ove_echo_red_noprefix "${err_string}"
 			exit 1
@@ -138,9 +190,9 @@ function main() {
 		find "${PWD}" -name '*.dmceoriginal' -exec rm  {} \;
 	fi
 
-	echo "$ ove buildme-parallel ${ove_proj}"
-	if ! ove buildme-parallel "${ove_proj}" > /dev/null; then
-		err_string="ove buildme-parallel ${ove_proj} failed"
+	echo "$ ove build ${ove_proj} && ove install ${ove_proj}"
+	if ! ove build "${ove_proj}" > /dev/null || ! ove install "${ove_proj}" > /dev/null; then
+		err_string="ove build or install ${ove_proj} failed"
 		ove_echo_red_noprefix "${err_string}"
 		if [ -s "${OVE_LAST_COMMAND}" ]; then
 			cat "${OVE_LAST_COMMAND}"
@@ -153,11 +205,14 @@ function main() {
 	fi
 
 	nbr_of_probes=$(git grep 'DMCE_PROBE([0-9]\+' | grep -o 'DMCE_PROBE([0-9]\+' | cut -d'(' -f2 | sort -V | tail -1)
-	echo "NOTE: repo '${git_full}' is instrumented with ${nbr_of_probes} probe(s). Run a testcase and when done run:"
-	echo "$ ove dmce-trace-decode ${git}"
-	echo
-	echo "Executable ELF files within the '${git}' repo:"
-	find ${git_full} -type f -perm -u=x -print -exec file {} \;| grep ELF | cut -d: -f1 | cat -n
+	echo "info: repo '${git_full}' is now instrumented with ${nbr_of_probes} probe(s). Run some test (executable files below) and then 'ove dmce trace-decode ${git}'"
+	elfs=$(find "${git_full}" -type f -perm -u=x -print -exec file {} \;| grep ELF | cut -d: -f1 | cat -n)
+	if [ "x$elfs" = "x" ]; then
+		echo "warning: no executable ELF files found in '${git}'. Building artifacts outside the git repo? Or did you select the wrong OVE project '$ove_proj'?"
+	else
+		echo "ELF files within the '${git}' repo:"
+		printf "%s\n" "$elfs"
+	fi
 
 	exit 0
 }
