ove: tabs to spaces

diff --git a/.ove/scripts/dmce b/.ove/scripts/dmce
--- a/.ove/scripts/dmce
+++ b/.ove/scripts/dmce
@@ -24,8 +24,8 @@
 # OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 if [ ! -e "${OVE_BASE_DIR:?}/.dmceconfig" ]; then
-	echo "error: '\$OVE_BASE_DIR/.dmceconfig' not found, try to install DMCE by running 'ove install dmce'"
-	exit 1
+    echo "error: '\$OVE_BASE_DIR/.dmceconfig' not found, try to install DMCE by running 'ove install dmce'"
+    exit 1
 fi
 
 default_args="-f ${OVE_BASE_DIR:?}/.dmceconfig"
@@ -64,26 +64,26 @@ LOW-LEVEL COMMANDS
 
 HIGH-LEVEL COMMANDS
 EOF
-	for f in "${OVE_ACTIVE_REPO_DIR}"/.ove/scripts/dmce-*; do
-		g=${f##*/}
-		if [[ $g == *.* ]]; then
-			continue
-		fi
-		g=${g/dmce-}
+    for f in "${OVE_ACTIVE_REPO_DIR}"/.ove/scripts/dmce-*; do
+        g=${f##*/}
+        if [[ $g == *.* ]]; then
+            continue
+        fi
+        g=${g/dmce-}
 
-		echo "        $g:"
-		echo "          # run 'ove dmce $g' for detailed description"
-		echo
-	done
-	echo "FILES"
-	echo "        \$OVE_BASE_DIR/.dmceconfig"
-	if [ -d "${OVE_BASE_DIR}"/.config/dmce ]; then
-		find "${OVE_BASE_DIR}"/.config/dmce | sed -e "s,$OVE_BASE_DIR,\$OVE_BASE_DIR," -e 's,^,        ,g'
-	else
-		echo "  ${OVE_BASE_DIR}/.config/dmce/*"
-	fi
-	echo
-	cat << EOF
+        echo "        $g:"
+        echo "          # run 'ove dmce $g' for detailed description"
+        echo
+    done
+    echo "FILES"
+    echo "        \$OVE_BASE_DIR/.dmceconfig"
+    if [ -d "${OVE_BASE_DIR}"/.config/dmce ]; then
+        find "${OVE_BASE_DIR}"/.config/dmce | sed -e "s,$OVE_BASE_DIR,\$OVE_BASE_DIR," -e 's,^,        ,g'
+    else
+        echo "  ${OVE_BASE_DIR}/.config/dmce/*"
+    fi
+    echo
+    cat << EOF
 EXAMPLES
         # set 'trace' profile
         $ ove dmce set-profile trace
@@ -97,117 +97,117 @@ EOF
 }
 
 function _getopts {
-	local args
+    local args
 
-	args="$*"
-	if [[ ${args} = *--[[:space:]]* ]]; then
-		opts=${args%%-- *}
-		repos=${args##*--}
-		repos="${repos//${OVE_BASE_DIR}\//}"
-	else
-		opts=${args}
-		repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	fi
+    args="$*"
+    if [[ ${args} = *--[[:space:]]* ]]; then
+        opts=${args%%-- *}
+        repos=${args##*--}
+        repos="${repos//${OVE_BASE_DIR}\//}"
+    else
+        opts=${args}
+        repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+    fi
 }
 
 # $1: prog
 function _find {
-	# try to find binary
-	if ! command -v "${1}" > /dev/null; then
-		prog="${OVE_ACTIVE_REPO_DIR:?}/${1}"
-	else
-		prog="$(command -v "${1}")"
-	fi
+    # try to find binary
+    if ! command -v "${1}" > /dev/null; then
+        prog="${OVE_ACTIVE_REPO_DIR:?}/${1}"
+    else
+        prog="$(command -v "${1}")"
+    fi
 
-	if [ ! -e "${prog}" ]; then
-		echo "error: can not find '${1}'"
-		exit 1
-	fi
+    if [ ! -e "${prog}" ]; then
+        echo "error: can not find '${1}'"
+        exit 1
+    fi
 }
 
 function run {
-	echo "$ ${prog} ${opts}" 1>&2
-	eval "${prog}" "${opts}"
+    echo "$ ${prog} ${opts}" 1>&2
+    eval "${prog}" "${opts}"
 }
 
 function set_profile {
-	local args
+    local args
 
-	shift
-	_find "dmce-set-profile"
-	_getopts "$@"
-	opts="$default_args -p -d $OVE_BASE_DIR/.config/dmce $opts"
-	run
+    shift
+    _find "dmce-set-profile"
+    _getopts "$@"
+    opts="$default_args -p -d $OVE_BASE_DIR/.config/dmce $opts"
+    run
 }
 
 function launch {
-	local opts
-	local r
-	local repos
+    local opts
+    local r
+    local repos
 
-	shift
+    shift
 
-	_find "dmce-launcher"
-	if [ $# -eq 0 ]; then
-		opts="-a -q"
-		repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	else
-		_getopts "$@"
-	fi
+    _find "dmce-launcher"
+    if [ $# -eq 0 ]; then
+        opts="-a -q"
+        repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+    else
+        _getopts "$@"
+    fi
 
-	opts="$default_args $opts"
-	for r in $repos; do
-		[ -d "$OVE_BASE_DIR"/"$r" ] || continue
-		cd "$OVE_BASE_DIR/$r" || continue
-		if [ "x$PWD" = "x${OVE_ACTIVE_REPO_DIR}" ]; then
-			continue
-		fi
-		run
-	done
+    opts="$default_args $opts"
+    for r in $repos; do
+        [ -d "$OVE_BASE_DIR"/"$r" ] || continue
+        cd "$OVE_BASE_DIR/$r" || continue
+        if [ "x$PWD" = "x${OVE_ACTIVE_REPO_DIR}" ]; then
+            continue
+        fi
+        run
+    done
 }
 
 function trace {
-	shift
-	_find "dmce-trace"
-	_getopts "$@"
-	run
+    shift
+    _find "dmce-trace"
+    _getopts "$@"
+    run
 }
 
 function summary_bin {
-	shift
-	_find "dmce-summary-bin"
-	_getopts "$@"
-	run
+    shift
+    _find "dmce-summary-bin"
+    _getopts "$@"
+    run
 }
 
 function summary_txt {
-	shift
-	_find "dmce-summary-txt"
-	_getopts "$@"
-	run
+    shift
+    _find "dmce-summary-txt"
+    _getopts "$@"
+    run
 }
 
 function main {
-	if [ $# -eq 0 ]; then
-		usage
-		exit 1
-	fi
+    if [ $# -eq 0 ]; then
+        usage
+        exit 1
+    fi
 
-	cmd=$1
-	n="${OVE_ACTIVE_REPO_DIR}/.ove/scripts/dmce-${cmd/_/-}"
-	if [ -s "${n}" ]; then
-		shift
-		if ! "${n}" "$@"; then
-			exit 1
-		fi
-	elif [ "x$(type -t "${1/-/_}")" != "xfunction" ]; then
-		echo "error: '$1' unknown command"
-		exit 1
-	else
-		if ! ${1/-/_} "$@"; then
-			exit 1
-		fi
-	fi
+    cmd=$1
+    n="${OVE_ACTIVE_REPO_DIR}/.ove/scripts/dmce-${cmd/_/-}"
+    if [ -s "${n}" ]; then
+        shift
+        if ! "${n}" "$@"; then
+            exit 1
+        fi
+    elif [ "x$(type -t "${1/-/_}")" != "xfunction" ]; then
+        echo "error: '$1' unknown command"
+        exit 1
+    else
+        if ! ${1/-/_} "$@"; then
+            exit 1
+        fi
+    fi
 }
 
 main "$@"
diff --git a/.ove/scripts/dmce-coverage-ahead b/.ove/scripts/dmce-coverage-ahead
--- a/.ove/scripts/dmce-coverage-ahead
+++ b/.ove/scripts/dmce-coverage-ahead
@@ -26,12 +26,12 @@
 name=$(basename "$0")
 
 function usage() {
-	local projs
-	local repos
+    local projs
+    local repos
 
-	repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	projs="${OVE_PROJECT_LIST}"
-	cat << EOF
+    repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+    projs="${OVE_PROJECT_LIST}"
+    cat << EOF
 NAME
        run coverage-history on commits not yet published
 
@@ -65,61 +65,61 @@ EOF
 }
 
 main() {
-	local git_full
+    local git_full
 
-	git="$1"
-	git_full="${OVE_BASE_DIR:?}/$1"
+    git="$1"
+    git_full="${OVE_BASE_DIR:?}/$1"
 
-	# usage and sanity checks
-	if [ $# -lt 3 ]; then
-		usage
-		exit 1
-	elif [ ! -d "${git_full}" ]; then
-		echo "error: ${git_full} is not a directory"
-		usage
-		exit 1
-	elif [ ! -d "${git_full}"/.git ]; then
-		echo "error: ${git_full} does not appear to be a git repo"
-		usage
-		exit 1
-	fi
+    # usage and sanity checks
+    if [ $# -lt 3 ]; then
+        usage
+        exit 1
+    elif [ ! -d "${git_full}" ]; then
+        echo "error: ${git_full} is not a directory"
+        usage
+        exit 1
+    elif [ ! -d "${git_full}"/.git ]; then
+        echo "error: ${git_full} does not appear to be a git repo"
+        usage
+        exit 1
+    fi
 
-	ove_proj="$2"
-	shift 2
-	mode="$@"
+    ove_proj="$2"
+    shift 2
+    mode="$@"
 
-	# get revs ahead for 'git'
-	mapfile -t revs <<<"$(ove-ahead "$git" | \grep -o '^[a-f0-9]\+')"
-	nbr_revs=${#revs[@]}
-	if [ "${nbr_revs}" -eq 0 ]; then
-		echo "error: no revs"
-		exit 1
-	elif [ "${nbr_revs}" -eq 1 ] && [ "x${revs[0]}" = "x" ]; then
-		echo "error: no revs"
-		exit 1
-	fi
+    # get revs ahead for 'git'
+    mapfile -t revs <<<"$(ove-ahead "$git" | \grep -o '^[a-f0-9]\+')"
+    nbr_revs=${#revs[@]}
+    if [ "${nbr_revs}" -eq 0 ]; then
+        echo "error: no revs"
+        exit 1
+    elif [ "${nbr_revs}" -eq 1 ] && [ "x${revs[0]}" = "x" ]; then
+        echo "error: no revs"
+        exit 1
+    fi
 
-	# get parent
-	if ! parent=$(git -C "$git_full" show "${revs[$((nbr_revs-1))]}"^1 --pretty=%H); then
-		exit 1
-	fi
-	revs+=("$parent")
-	nbr_revs=${#revs[@]}
+    # get parent
+    if ! parent=$(git -C "$git_full" show "${revs[$((nbr_revs-1))]}"^1 --pretty=%H); then
+        exit 1
+    fi
+    revs+=("$parent")
+    nbr_revs=${#revs[@]}
 
-	# sanity check
-	for i in $(seq 0 $((nbr_revs - 1))); do
-		if ! git -C "$git_full" cat-file -e "${revs[i]}" &> /dev/null; then
-			echo "error: '${revs[i]}' is not a valid rev"
-			exit 1
-		fi
-	done
+    # sanity check
+    for i in $(seq 0 $((nbr_revs - 1))); do
+        if ! git -C "$git_full" cat-file -e "${revs[i]}" &> /dev/null; then
+            echo "error: '${revs[i]}' is not a valid rev"
+            exit 1
+        fi
+    done
 
-	echo "revs (${nbr_revs}): ${revs[*]}"
+    echo "revs (${nbr_revs}): ${revs[*]}"
 
-	echo "run 'ove-dmce coverage-history $git $ove_proj $mode ${revs[*]}'"
-	if ! ove-dmce coverage-history "$git" "$ove_proj" $mode ${revs[*]}; then
-		exit 1
-	fi
+    echo "run 'ove-dmce coverage-history $git $ove_proj $mode ${revs[*]}'"
+    if ! ove-dmce coverage-history "$git" "$ove_proj" $mode ${revs[*]}; then
+        exit 1
+    fi
 }
 
 main "$@"
diff --git a/.ove/scripts/dmce-trace-decode b/.ove/scripts/dmce-trace-decode
--- a/.ove/scripts/dmce-trace-decode
+++ b/.ove/scripts/dmce-trace-decode
@@ -24,12 +24,12 @@
 # OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 function usage() {
-	local repos
+    local repos
 
-	repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	repos="${repos/dmce/}"
-	repos="${repos/  / }"
-	cat << EOF
+    repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+    repos="${repos/dmce/}"
+    repos="${repos/  / }"
+    cat << EOF
 NAME
         Decode DMCE trace buffer
 
@@ -41,7 +41,7 @@ OPTIONS
           choose one git of: ${repos}
 
 PREREQUISITE
-	A successful run of 'ove dmce trace-prepare'
+    A successful run of 'ove dmce trace-prepare'
 
 DESCRIPTION
         This OVE plugin will decode one DMCE trace buffer and display the raw trace to the user.
@@ -66,308 +66,308 @@ EXAMPLES
         # decode the trace buffer and save the trace to a file '/tmp/a.trace'
         $ DMCE_TRACE_VIEWER=/tmp/a.trace ove dmce trace-decode ag
 EOF
-	exit 1
+    exit 1
 }
 
 function init() {
-	# usage and sanity checks
-	if [ $# -ne 1 ]; then
-		usage
-	fi
+    # usage and sanity checks
+    if [ $# -ne 1 ]; then
+        usage
+    fi
 
-	git="$1"
-	git_base="${1##*/}"
-	git_full="${OVE_BASE_DIR:?}/$1"
-	name="$(basename "$0")-${git/\//_}"
+    git="$1"
+    git_base="${1##*/}"
+    git_full="${OVE_BASE_DIR:?}/$1"
+    name="$(basename "$0")-${git/\//_}"
 
-	if [ ! -d "${git_full}" ]; then
-		echo "error: ${git_full} is not a directory"
-		usage
-	elif [ ! -d "${git_full}"/.git ]; then
-		echo "error: ${git_full} does not appear to be a git repo"
-		usage
-	fi
+    if [ ! -d "${git_full}" ]; then
+        echo "error: ${git_full} is not a directory"
+        usage
+    elif [ ! -d "${git_full}"/.git ]; then
+        echo "error: ${git_full} does not appear to be a git repo"
+        usage
+    fi
 
-	if ! cd "${git_full}"; then
-		echo "error: 'cd ${git_full}' failed, weird!"
-		exit 1
-	fi
+    if ! cd "${git_full}"; then
+        echo "error: 'cd ${git_full}' failed, weird!"
+        exit 1
+    fi
 }
 
 function cleanup() {
-	for f in $files; do
-		if [ -e "$f" ]; then
-			rm "$f"
-		fi
-	done
+    for f in $files; do
+        if [ -e "$f" ]; then
+            rm "$f"
+        fi
+    done
 }
 
 function main() {
-	init "$@"
+    init "$@"
 
-	trap cleanup EXIT
+    trap cleanup EXIT
 
-	# nothing probed, see if we have something in the git stash
-	if ! git grep -q 'DMCE_PROBE('; then
-		stash=$(git stash list | grep 'dmce')
-		if [ "x$stash" = "x" ]; then
-			echo "error: nothing saved in stash for '$git', try to run 'ove dmce-trace-prepare $git ...'"
-			exit 1
-		fi
+    # nothing probed, see if we have something in the git stash
+    if ! git grep -q 'DMCE_PROBE('; then
+        stash=$(git stash list | grep 'dmce')
+        if [ "x$stash" = "x" ]; then
+            echo "error: nothing saved in stash for '$git', try to run 'ove dmce-trace-prepare $git ...'"
+            exit 1
+        fi
 
-		nbr_stash=$(printf "%s\n" "$stash" | wc -l)
-		if [ "$nbr_stash" -eq 1 ]; then
-			stash_idx="$(printf "%s\n" "$stash" | cut -d: -f1)"
-			echo "$ git -C ${git_full} pop -q $stash_idx"
-			if ! git stash pop -q "$stash_idx"; then
-				exit 1
-			fi
-		else
-			read -t 3 -p "use stashed instrumentation (this dialog will timeout in 3 seconds and use the latest stash)? (Y/n) " -r
-			ret=$?
-			# timeout? use the first stash
-			if [ $ret -gt 128 ]; then
-				echo
-				stash_idx="$(printf "%s\n" "$stash" | cut -d: -f1 | head -1)"
-				echo "$ git -C ${git_full} pop -q $stash_idx"
-				if ! git stash pop -q "$stash_idx"; then
-					exit 1
-				fi
-			elif [[ ${REPLY} =~ ^[Yy]$ ]]; then
-				printf "%s\n" "$stash"
-				read -p "stash: " -r
-				if ! [[ "${REPLY}" =~ ^[0-9]+$ ]]; then
-					[ "${REPLY}" != "" ] && \
-						echo "error: just numbers"
-					exit 1
-				fi
+        nbr_stash=$(printf "%s\n" "$stash" | wc -l)
+        if [ "$nbr_stash" -eq 1 ]; then
+            stash_idx="$(printf "%s\n" "$stash" | cut -d: -f1)"
+            echo "$ git -C ${git_full} pop -q $stash_idx"
+            if ! git stash pop -q "$stash_idx"; then
+                exit 1
+            fi
+        else
+            read -t 3 -p "use stashed instrumentation (this dialog will timeout in 3 seconds and use the latest stash)? (Y/n) " -r
+            ret=$?
+            # timeout? use the first stash
+            if [ $ret -gt 128 ]; then
+                echo
+                stash_idx="$(printf "%s\n" "$stash" | cut -d: -f1 | head -1)"
+                echo "$ git -C ${git_full} pop -q $stash_idx"
+                if ! git stash pop -q "$stash_idx"; then
+                    exit 1
+                fi
+            elif [[ ${REPLY} =~ ^[Yy]$ ]]; then
+                printf "%s\n" "$stash"
+                read -p "stash: " -r
+                if ! [[ "${REPLY}" =~ ^[0-9]+$ ]]; then
+                    [ "${REPLY}" != "" ] && \
+                        echo "error: just numbers"
+                    exit 1
+                fi
 
-				echo "$ git -C ${git_full} pop -q stash@{$REPLY}"
-				if ! git stash pop -q "stash@{$REPLY}"; then
-					exit 1
-				fi
-			fi
-		fi
+                echo "$ git -C ${git_full} pop -q stash@{$REPLY}"
+                if ! git stash pop -q "stash@{$REPLY}"; then
+                    exit 1
+                fi
+            fi
+        fi
 
-		# sanity check
-		if ! git grep -q 'DMCE_PROBE('; then
-			echo "error: the code is not instrumented, try to run 'ove dmce-trace-prepare'"
-			exit 1
-		fi
-	fi
+        # sanity check
+        if ! git grep -q 'DMCE_PROBE('; then
+            echo "error: the code is not instrumented, try to run 'ove dmce-trace-prepare'"
+            exit 1
+        fi
+    fi
 
-	dmce_trace_log="$OVE_TMP/$name.log"
-	dmce_trace_args=
-	dmce_trace_args+=" --delimiter @"
-	dmce_trace_args+=" --format raw"
-	dmce_trace_args+=" --numvars 5"
-	dmce_trace_args+=" -t"
-	dmce_trace_args+=" /tmp/$OVE_USER/dmce/dmcebuffer.bin"
-	dmce_trace_args+=" /tmp/$OVE_USER/dmce/${git_base}/probe-references.log"
-	dmce_trace_args+=" ${git_full}"
+    dmce_trace_log="$OVE_TMP/$name.log"
+    dmce_trace_args=
+    dmce_trace_args+=" --delimiter @"
+    dmce_trace_args+=" --format raw"
+    dmce_trace_args+=" --numvars 5"
+    dmce_trace_args+=" -t"
+    dmce_trace_args+=" /tmp/$OVE_USER/dmce/dmcebuffer.bin"
+    dmce_trace_args+=" /tmp/$OVE_USER/dmce/${git_base}/probe-references.log"
+    dmce_trace_args+=" ${git_full}"
 
-	fzf=0
-	# not set, select fzf if it's available
-	if [ "x$DMCE_TRACE_VIEWER" = "x" ]; then
-		if ! command -v fzf > /dev/null; then
-			fzf=0
-			dmce_trace_args+=" --hl"
-		else
-			fzf=1
-		fi
-	elif [ "x$DMCE_TRACE_VIEWER" = "xfzf" ]; then
-		# fzf is forced but not available, fallback to 'less'
-		if ! command -v fzf > /dev/null; then
-			fzf=0
-		else
-			fzf=1
-		fi
-	else
-		# fzf is 0, select less/stdout/stderr/file below
-		:
-	fi
+    fzf=0
+    # not set, select fzf if it's available
+    if [ "x$DMCE_TRACE_VIEWER" = "x" ]; then
+        if ! command -v fzf > /dev/null; then
+            fzf=0
+            dmce_trace_args+=" --hl"
+        else
+            fzf=1
+        fi
+    elif [ "x$DMCE_TRACE_VIEWER" = "xfzf" ]; then
+        # fzf is forced but not available, fallback to 'less'
+        if ! command -v fzf > /dev/null; then
+            fzf=0
+        else
+            fzf=1
+        fi
+    else
+        # fzf is 0, select less/stdout/stderr/file below
+        :
+    fi
 
-	echo "$ ove-dmce-trace ${dmce_trace_args}"
-	if ! ove-dmce trace ${dmce_trace_args} > ${dmce_trace_log}; then
-		echo "error: 'ove-dmce-trace ${dmce_trace_args}' failed"
-		exit 1
-	fi
+    echo "$ ove-dmce-trace ${dmce_trace_args}"
+    if ! ove-dmce trace ${dmce_trace_args} > ${dmce_trace_log}; then
+        echo "error: 'ove-dmce-trace ${dmce_trace_args}' failed"
+        exit 1
+    fi
 
-	# sanity check
-	if [ ! -s ${dmce_trace_log} ]; then
-		echo "error: dmce-trace was successful but we got no output"
-		exit 1
-	fi
-	files+=" ${dmce_trace_log}"
+    # sanity check
+    if [ ! -s ${dmce_trace_log} ]; then
+        echo "error: dmce-trace was successful but we got no output"
+        exit 1
+    fi
+    files+=" ${dmce_trace_log}"
 
-	echo "$ cd ${git_full}"
-	if ! cd "${git_full}"; then
-		echo "error: 'cd ${git_full}' failed, weird!"
-		exit 1
-	fi
+    echo "$ cd ${git_full}"
+    if ! cd "${git_full}"; then
+        echo "error: 'cd ${git_full}' failed, weird!"
+        exit 1
+    fi
 
-	if [ $fzf -eq 1 ]; then
-		# get prolog length
-		random_file=$(git grep 'DMCE_PROBE(' | cut -d: -f1 | tail -1)
-		if [ "x${random_file}" = "x" ]; then
-			echo "error: weird, random probed file not found"
-			exit 1
-		fi
+    if [ $fzf -eq 1 ]; then
+        # get prolog length
+        random_file=$(git grep 'DMCE_PROBE(' | cut -d: -f1 | tail -1)
+        if [ "x${random_file}" = "x" ]; then
+            echo "error: weird, random probed file not found"
+            exit 1
+        fi
 
-		c=$(git diff -- $random_file | grep -m1 '^@@')
-		b=$(echo "$c" | cut -d',' -f3| cut -d' ' -f1)
-		a=$(echo "$c" | cut -d',' -f2| cut -d' ' -f1)
-		export DMCE_PROLOG_LEN=$((b-a))
-		DMCE_PROLOG_LEN=$((DMCE_PROLOG_LEN-1))
-		export DMCE_PLUS_SIGN="+"
+        c=$(git diff -- $random_file | grep -m1 '^@@')
+        b=$(echo "$c" | cut -d',' -f3| cut -d' ' -f1)
+        a=$(echo "$c" | cut -d',' -f2| cut -d' ' -f1)
+        export DMCE_PROLOG_LEN=$((b-a))
+        DMCE_PROLOG_LEN=$((DMCE_PROLOG_LEN-1))
+        export DMCE_PLUS_SIGN="+"
 
-		# swap core and timestamp
-		# add fullpath to file
-		sed -i -e "s,^\([0-9]\+\) @\([0-9]\+\)@\(.*$\),\2@\1@$OVE_BASE_DIR/$git/\3,g" "${dmce_trace_log}"
-		true > ${dmce_trace_log}_view
-		while IFS='@' read -r core ts f n func line vars; do
-			printf "%s\n" "$core@$ts@$f@+$((n - DMCE_PROLOG_LEN))@$func@$line@$vars"
-		done <${dmce_trace_log} | column -t -s@ > ${dmce_trace_log}_view
-		files+=" ${dmce_trace_log}_view"
+        # swap core and timestamp
+        # add fullpath to file
+        sed -i -e "s,^\([0-9]\+\) @\([0-9]\+\)@\(.*$\),\2@\1@$OVE_BASE_DIR/$git/\3,g" "${dmce_trace_log}"
+        true > ${dmce_trace_log}_view
+        while IFS='@' read -r core ts f n func line vars; do
+            printf "%s\n" "$core@$ts@$f@+$((n - DMCE_PROLOG_LEN))@$func@$line@$vars"
+        done <${dmce_trace_log} | column -t -s@ > ${dmce_trace_log}_view
+        files+=" ${dmce_trace_log}_view"
 
-	fi
+    fi
 
-	# remove previous stash(es)
-	while true; do
-		stash=$(git stash list | grep 'dmce@' | head -1 | cut -d':' -f1)
-		if [ "x${stash}" = "x" ]; then
-			break
-		fi
-		echo "$ git -C ${git_full} stash drop ${stash}"
-		git stash drop "${stash}"
-	done
+    # remove previous stash(es)
+    while true; do
+        stash=$(git stash list | grep 'dmce@' | head -1 | cut -d':' -f1)
+        if [ "x${stash}" = "x" ]; then
+            break
+        fi
+        echo "$ git -C ${git_full} stash drop ${stash}"
+        git stash drop "${stash}"
+    done
 
-	now=$(\date '+%Y%m%d-%H%M%S')
-	stash_msg="dmce@$now: #probes:$(wc -l < /tmp/$OVE_USER/dmce/$git/probe-references.log) #prolog:$DMCE_PROLOG_LEN stat:$(git diff --shortstat)"
-	echo "$ git -C ${git_full} stash -m $stash_msg"
-	if ! git -C ${git_full} stash push -q -m "$stash_msg"; then
-		echo "error: 'git stash push' failed"
-		exit 1
-	fi
+    now=$(\date '+%Y%m%d-%H%M%S')
+    stash_msg="dmce@$now: #probes:$(wc -l < /tmp/$OVE_USER/dmce/$git/probe-references.log) #prolog:$DMCE_PROLOG_LEN stat:$(git diff --shortstat)"
+    echo "$ git -C ${git_full} stash -m $stash_msg"
+    if ! git -C ${git_full} stash push -q -m "$stash_msg"; then
+        echo "error: 'git stash push' failed"
+        exit 1
+    fi
 
-	# restore any local modifications saved by 'dmce-trace-prepare'
-	dmce_trace_diff="$OVE_TMP/dmce-trace-prepare-$git.diff"
-	if [ -s "${dmce_trace_diff}" ]; then
-		git apply "${dmce_trace_diff}" 2> /dev/null
-	fi
-	# none-fzf: simply display the log
-	if [ $fzf -eq 0 ]; then
-		if [ "x$DMCE_TRACE_VIEWER" = "x" ] || [ "x$DMCE_TRACE_VIEWER" = "xstdout" ]; then
-			column -t -s'@' ${dmce_trace_log}
-		elif [ "x$DMCE_TRACE_VIEWER" = "xless" ]; then
-			column -t -s'@' ${dmce_trace_log} | less -r
-		elif [ "x$DMCE_TRACE_VIEWER" = "xstderr" ]; then
-			column -t -s'@' ${dmce_trace_log} 1>&2
-		else
-			echo "saving trace as '$(readlink -f $DMCE_TRACE_VIEWER)'"
-			if ! column -t -s'@' ${dmce_trace_log} > $DMCE_TRACE_VIEWER; then
-				exit 1
-			fi
-		fi
+    # restore any local modifications saved by 'dmce-trace-prepare'
+    dmce_trace_diff="$OVE_TMP/dmce-trace-prepare-$git.diff"
+    if [ -s "${dmce_trace_diff}" ]; then
+        git apply "${dmce_trace_diff}" 2> /dev/null
+    fi
+    # none-fzf: simply display the log
+    if [ $fzf -eq 0 ]; then
+        if [ "x$DMCE_TRACE_VIEWER" = "x" ] || [ "x$DMCE_TRACE_VIEWER" = "xstdout" ]; then
+            column -t -s'@' ${dmce_trace_log}
+        elif [ "x$DMCE_TRACE_VIEWER" = "xless" ]; then
+            column -t -s'@' ${dmce_trace_log} | less -r
+        elif [ "x$DMCE_TRACE_VIEWER" = "xstderr" ]; then
+            column -t -s'@' ${dmce_trace_log} 1>&2
+        else
+            echo "saving trace as '$(readlink -f $DMCE_TRACE_VIEWER)'"
+            if ! column -t -s'@' ${dmce_trace_log} > $DMCE_TRACE_VIEWER; then
+                exit 1
+            fi
+        fi
 
-		exit 0
-	fi
+        exit 0
+    fi
 
-	# fzf only below...
-	t_old="${OVE_TMP}/$name.told"
-	true > "${t_old}"
-	files+=" ${t_old}"
+    # fzf only below...
+    t_old="${OVE_TMP}/$name.told"
+    true > "${t_old}"
+    files+=" ${t_old}"
 
-	preview_left="${OVE_TMP}/$name.left"
-	preview_right="${OVE_TMP}/$name.right"
-	files+=" $preview_left"
-	files+=" $preview_right"
+    preview_left="${OVE_TMP}/$name.left"
+    preview_right="${OVE_TMP}/$name.right"
+    files+=" $preview_left"
+    files+=" $preview_right"
 
-	< ${dmce_trace_log}_view fzf \
-		--tac \
-		--preview-window=down \
-		--preview '
-		lineno={n}
-		((lineno++))
-		# get core
-		c=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f1)
+    < ${dmce_trace_log}_view fzf \
+        --tac \
+        --preview-window=down \
+        --preview '
+        lineno={n}
+        ((lineno++))
+        # get core
+        c=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f1)
 
-		# timestamp
-		t=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f2)
+        # timestamp
+        t=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f2)
 
-		if [ -s '${t_old}' ]; then
-			t_old=$(cat '${t_old}');
-			if [ $t -ge $t_old ]; then
-				t_diff=$((t-t_old))
-			else
-				t_diff=$((t_old-t))
-			fi
-		else
-			t_old=0
-			t_diff=0
-		fi
-		# save old t value
-		echo "$t" > '${t_old}';
+        if [ -s '${t_old}' ]; then
+            t_old=$(cat '${t_old}');
+            if [ $t -ge $t_old ]; then
+                t_diff=$((t-t_old))
+            else
+                t_diff=$((t_old-t))
+            fi
+        else
+            t_old=0
+            t_diff=0
+        fi
+        # save old t value
+        echo "$t" > '${t_old}';
 
-		# get filename
-		f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3)
+        # get filename
+        f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3)
 
-		# get line number
-		n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4 | cut -b2-)
+        # get line number
+        n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4 | cut -b2-)
 
-		# compensate for prolog
-		n=$((n-'$DMCE_PROLOG_LEN'))
+        # compensate for prolog
+        n=$((n-'$DMCE_PROLOG_LEN'))
 
-		# get func name
-		func=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f5 | xargs)
+        # get func name
+        func=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f5 | xargs)
 
-		# get variables
-		vars=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f7)
+        # get variables
+        vars=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f7)
 
-		# display filename, line, core and diff at the top
-		echo "$f +$n core: $c diff: $t_diff"
+        # display filename, line, core and diff at the top
+        echo "$f +$n core: $c diff: $t_diff"
 
-		# delimiter
-		echo "---"
+        # delimiter
+        echo "---"
 
-		# number of lines
-		f_len=$(wc -l < $f)
+        # number of lines
+        f_len=$(wc -l < $f)
 
-		# the whole file fit in the preview window?
-		if [ $f_len -lt $FZF_PREVIEW_LINES ]; then
-			p_lines=$((FZF_PREVIEW_LINES))
-		# is current line above halv preview?
-		elif [ $n -lt $((FZF_PREVIEW_LINES/2)) ]; then
-			p_lines=$((FZF_PREVIEW_LINES))
-		else
-			p_lines=$((FZF_PREVIEW_LINES/2))
-		fi
+        # the whole file fit in the preview window?
+        if [ $f_len -lt $FZF_PREVIEW_LINES ]; then
+            p_lines=$((FZF_PREVIEW_LINES))
+        # is current line above halv preview?
+        elif [ $n -lt $((FZF_PREVIEW_LINES/2)) ]; then
+            p_lines=$((FZF_PREVIEW_LINES))
+        else
+            p_lines=$((FZF_PREVIEW_LINES/2))
+        fi
 
-		# default grep colors
-		if [ ! -v GREP_COLORS ]; then
-			export GREP_COLORS="ms=38;5;0;48;5;14"
-		fi
+        # default grep colors
+        if [ ! -v GREP_COLORS ]; then
+            export GREP_COLORS="ms=38;5;0;48;5;14"
+        fi
 
-		# get the whole file with line numbers
-		# highlight our line
-		grep -n ".*" $f | grep -C$p_lines "^$n:.*" | grep -C$p_lines --color=always -E "^$n:.*" > '${preview_left}'
+        # get the whole file with line numbers
+        # highlight our line
+        grep -n ".*" $f | grep -C$p_lines "^$n:.*" | grep -C$p_lines --color=always -E "^$n:.*" > '${preview_left}'
 
-		# sort the variables and do some pretty printing
-		printf "%s\n" $vars | sort | column -t -s: | sed -e "s,^,  ,g" > '${preview_right}'
+        # sort the variables and do some pretty printing
+        printf "%s\n" $vars | sort | column -t -s: | sed -e "s,^,  ,g" > '${preview_right}'
 
-		# calclulate the length of the two files
-		left_len=$(wc -l < '${preview_left}')
-		right_len=$(wc -l < '${preview_right}')
+        # calclulate the length of the two files
+        left_len=$(wc -l < '${preview_left}')
+        right_len=$(wc -l < '${preview_right}')
 
-		# use pr to produce some nice columns
-		pr -w $FZF_PREVIEW_COLUMNS -e -t -m <(head -$right_len '${preview_left}') <(head -$right_len '${preview_right}')
+        # use pr to produce some nice columns
+        pr -w $FZF_PREVIEW_COLUMNS -e -t -m <(head -$right_len '${preview_left}') <(head -$right_len '${preview_right}')
 
-		# display the remaining part of the file
-		tail -n +$((right_len+1)) '${preview_left}'' \
-			--bind 'enter:execute(     lineno={n}; ((lineno++)); < /dev/tty eval $(f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3); n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4); n=$((n-DMCE_PROLOG_LEN)); echo "vim $f $DMCE_PLUS_SIGN$n"))' \
-			--bind 'left-click:execute(lineno={n}; ((lineno++)); < /dev/tty eval $(f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3); n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4); n=$((n-DMCE_PROLOG_LEN)); echo "vim $f $DMCE_PLUS_SIGN$n"))'
+        # display the remaining part of the file
+        tail -n +$((right_len+1)) '${preview_left}'' \
+            --bind 'enter:execute(     lineno={n}; ((lineno++)); < /dev/tty eval $(f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3); n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4); n=$((n-DMCE_PROLOG_LEN)); echo "vim $f $DMCE_PLUS_SIGN$n"))' \
+            --bind 'left-click:execute(lineno={n}; ((lineno++)); < /dev/tty eval $(f=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f3); n=$(sed "${lineno}!d" '${dmce_trace_log}' | cut -d@ -f4); n=$((n-DMCE_PROLOG_LEN)); echo "vim $f $DMCE_PLUS_SIGN$n"))'
 
-	exit 0
+    exit 0
 }
 
 main "$@"
diff --git a/.ove/scripts/dmce-trace-prepare b/.ove/scripts/dmce-trace-prepare
--- a/.ove/scripts/dmce-trace-prepare
+++ b/.ove/scripts/dmce-trace-prepare
@@ -24,13 +24,13 @@
 # OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 
 function usage() {
-	local projs
-	local repos
+    local projs
+    local repos
 
-	repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
-	repos="${repos/  / }"
-	projs="${OVE_PROJECT_LIST}"
-	cat << EOF
+    repos="${OVE_REPO_LIST//${OVE_BASE_DIR}\//}"
+    repos="${repos/  / }"
+    projs="${OVE_PROJECT_LIST}"
+    cat << EOF
 NAME
         Insert DMCE probes into one repo and build it
 
@@ -69,152 +69,152 @@ EOF
 }
 
 function main() {
-	git="$1"
-	ove_proj="$2"
-	git_full="${OVE_BASE_DIR:?}/$1"
+    git="$1"
+    ove_proj="$2"
+    git_full="${OVE_BASE_DIR:?}/$1"
 
-	# usage and sanity checks
-	if [ $# -lt 2 ]; then
-		usage
-		exit 1
-	elif [ ! -d "${git_full}" ]; then
-		echo "error: ${git_full} is not a directory"
-		usage
-		exit 1
-	elif [ ! -d "${git_full}"/.git ]; then
-		echo "error: ${git_full} does not appear to be a git repo"
-		usage
-		exit 1
-	fi
+    # usage and sanity checks
+    if [ $# -lt 2 ]; then
+        usage
+        exit 1
+    elif [ ! -d "${git_full}" ]; then
+        echo "error: ${git_full} is not a directory"
+        usage
+        exit 1
+    elif [ ! -d "${git_full}"/.git ]; then
+        echo "error: ${git_full} does not appear to be a git repo"
+        usage
+        exit 1
+    fi
 
-	name="$(basename "$0")-${git/\//_}"
+    name="$(basename "$0")-${git/\//_}"
 
-	echo "$ cd ${git_full}"
-	if ! cd "${git_full}"; then
-		echo "error: 'cd ${git_full}' failed, weird!"
-		exit 1
-	fi
+    echo "$ cd ${git_full}"
+    if ! cd "${git_full}"; then
+        echo "error: 'cd ${git_full}' failed, weird!"
+        exit 1
+    fi
 
-	launch=1
-	stash=$(git stash list | grep 'dmce')
-	if [ "x${DMCE_TRACE_AUTOMATION}" = "x" ] && [ "x${stash}" != "x" ]; then
-		printf "%s\n" "$stash"
-		read -t 10 -p "use stashed instrumentation (this dialog will timeout in 10 seconds)? (y/N) " -r
-		ret=$?
-		if [ ${ret} -gt 128 ]; then
-			echo
-		elif [[ ${REPLY} =~ ^[Yy]$ ]]; then
-			printf "%s\n" "$stash"
-			nbr_stash=$(printf "%s\n" "$stash" | wc -l)
-			if [ "${nbr_stash}" -eq 1 ]; then
-				stash_idx="$(printf "%s\n" "${stash}" | cut -d: -f1)"
-				echo "$ git -C ${git_full} pop -q ${stash_idx}"
-				if ! git stash pop -q "${stash_idx}"; then
-					exit 1
-				fi
-			else
-				read -p "stash: " -r
-				if ! [[ "${REPLY}" =~ ^[0-9]+$ ]]; then
-					[ "${REPLY}" != "" ] && \
-						echo "error: just numbers"
-					exit 1
-				fi
+    launch=1
+    stash=$(git stash list | grep 'dmce')
+    if [ "x${DMCE_TRACE_AUTOMATION}" = "x" ] && [ "x${stash}" != "x" ]; then
+        printf "%s\n" "$stash"
+        read -t 10 -p "use stashed instrumentation (this dialog will timeout in 10 seconds)? (y/N) " -r
+        ret=$?
+        if [ ${ret} -gt 128 ]; then
+            echo
+        elif [[ ${REPLY} =~ ^[Yy]$ ]]; then
+            printf "%s\n" "$stash"
+            nbr_stash=$(printf "%s\n" "$stash" | wc -l)
+            if [ "${nbr_stash}" -eq 1 ]; then
+                stash_idx="$(printf "%s\n" "${stash}" | cut -d: -f1)"
+                echo "$ git -C ${git_full} pop -q ${stash_idx}"
+                if ! git stash pop -q "${stash_idx}"; then
+                    exit 1
+                fi
+            else
+                read -p "stash: " -r
+                if ! [[ "${REPLY}" =~ ^[0-9]+$ ]]; then
+                    [ "${REPLY}" != "" ] && \
+                        echo "error: just numbers"
+                    exit 1
+                fi
 
-				if ! git stash pop -q "stash@{$REPLY}"; then
-					exit 1
-				fi
-			fi
-			launch=0
-		fi
-	fi
+                if ! git stash pop -q "stash@{$REPLY}"; then
+                    exit 1
+                fi
+            fi
+            launch=0
+        fi
+    fi
 
-	if [ ${launch} -eq 1 ]; then
-		echo "$ ove-dmce set-profile trace"
-		if ! ove-dmce set-profile trace; then
-			echo "error: 'ove dmce set-profile trace' failed"
-			exit 1
-		fi
+    if [ ${launch} -eq 1 ]; then
+        echo "$ ove-dmce set-profile trace"
+        if ! ove-dmce set-profile trace; then
+            echo "error: 'ove dmce set-profile trace' failed"
+            exit 1
+        fi
 
-		if git -C "${git_full}" grep -q 'DMCE_PROBE('; then
-			if [ "x${DMCE_TRACE_AUTOMATION}" != "x" ] && [ "${DMCE_TRACE_AUTOMATION}" -eq 1 ]; then
-				# do nothing
-				true
-			else
-				read -r -p "info: repo '${git}' is already probed! git stash && git stash drop? (y/N)"
-				if ! [[ ${REPLY} =~ ^[Yy]$ ]]; then
-					exit 1
-				fi
-			fi
+        if git -C "${git_full}" grep -q 'DMCE_PROBE('; then
+            if [ "x${DMCE_TRACE_AUTOMATION}" != "x" ] && [ "${DMCE_TRACE_AUTOMATION}" -eq 1 ]; then
+                # do nothing
+                true
+            else
+                read -r -p "info: repo '${git}' is already probed! git stash && git stash drop? (y/N)"
+                if ! [[ ${REPLY} =~ ^[Yy]$ ]]; then
+                    exit 1
+                fi
+            fi
 
-			if ! git -C "${git_full}" stash -q; then
-				ove-echo red "error: 'git -C ${git_full} stash' failed"
-				exit 1
-			fi
+            if ! git -C "${git_full}" stash -q; then
+                ove-echo red "error: 'git -C ${git_full} stash' failed"
+                exit 1
+            fi
 
-			if ! git -C "${git_full}" stash drop -q; then
-				ove-echo red "error: 'git -C ${git_full} stash drop' failed"
-				exit 1
-			fi
-		fi
+            if ! git -C "${git_full}" stash drop -q; then
+                ove-echo red "error: 'git -C ${git_full} stash drop' failed"
+                exit 1
+            fi
+        fi
 
-		# save any local modifications
-		dmce_trace_diff="${OVE_TMP}/${name}.diff"
-		git diff > "${dmce_trace_diff}"
-		if [ -s "${dmce_trace_diff}" ]; then
-			echo "$ git diff > ${dmce_trace_diff}"
-		else
-			rm "${dmce_trace_diff}"
-		fi
+        # save any local modifications
+        dmce_trace_diff="${OVE_TMP}/${name}.diff"
+        git diff > "${dmce_trace_diff}"
+        if [ -s "${dmce_trace_diff}" ]; then
+            echo "$ git diff > ${dmce_trace_diff}"
+        else
+            rm "${dmce_trace_diff}"
+        fi
 
-		echo "$ ove-dmce launch -a -- $git_full"
-		out=$(ove-dmce launch -a -- "$git_full")
-		ret=$?
-		if [ ${ret} -ne 0 ]; then
-			if [[ ${out} == *error* ]]; then
-				err_string="$(echo "${out}"| grep error: | sed 's,error: ,,g')"
-			else
-				err_string="'ove-dmce launch -a -- $git_full' failed"
-			fi
-			ove-echo red "${err_string}"
-			exit 1
-		fi
+        echo "$ ove-dmce launch -a -- $git_full"
+        out=$(ove-dmce launch -a -- "$git_full")
+        ret=$?
+        if [ ${ret} -ne 0 ]; then
+            if [[ ${out} == *error* ]]; then
+                err_string="$(echo "${out}"| grep error: | sed 's,error: ,,g')"
+            else
+                err_string="'ove-dmce launch -a -- $git_full' failed"
+            fi
+            ove-echo red "${err_string}"
+            exit 1
+        fi
 
-		# still no probes?
-		if ! git grep -q 'DMCE_PROBE('; then
-			err_string="no probes inserted"
-			ove-echo red "${err_string}"
-			exit 1
-		fi
+        # still no probes?
+        if ! git grep -q 'DMCE_PROBE('; then
+            err_string="no probes inserted"
+            ove-echo red "${err_string}"
+            exit 1
+        fi
 
-		# clean
-		find "${PWD}" -name '*.dmceoriginal' -exec rm  {} \;
-	fi
+        # clean
+        find "${PWD}" -name '*.dmceoriginal' -exec rm  {} \;
+    fi
 
-	echo "$ ove build ${ove_proj} && ove install ${ove_proj}"
-	if ! ove build "${ove_proj}" > /dev/null || ! ove install "${ove_proj}" > /dev/null; then
-		err_string="ove build or install ${ove_proj} failed"
-		ove-echo red "${err_string}"
-		if [ -s "${OVE_LAST_COMMAND}" ]; then
-			cat "${OVE_LAST_COMMAND}"
-		fi
+    echo "$ ove build ${ove_proj} && ove install ${ove_proj}"
+    if ! ove build "${ove_proj}" > /dev/null || ! ove install "${ove_proj}" > /dev/null; then
+        err_string="ove build or install ${ove_proj} failed"
+        ove-echo red "${err_string}"
+        if [ -s "${OVE_LAST_COMMAND}" ]; then
+            cat "${OVE_LAST_COMMAND}"
+        fi
 
-		# remove DMCE probes and keep local modifications
-		git stash; git stash drop -q
-		git apply "${dmce_trace_diff}"
-		exit 1
-	fi
+        # remove DMCE probes and keep local modifications
+        git stash; git stash drop -q
+        git apply "${dmce_trace_diff}"
+        exit 1
+    fi
 
-	nbr_of_probes=$(git grep 'DMCE_PROBE([0-9]\+' | grep -o 'DMCE_PROBE([0-9]\+' | cut -d'(' -f2 | sort -V | tail -1)
-	echo "info: repo '${git_full}' is now instrumented with ${nbr_of_probes} probe(s). Run some test (executable files below) and then 'ove dmce trace-decode ${git}'"
-	elfs=$(find "${git_full}" -type f -perm -u=x -print -exec file {} \;| grep ELF | cut -d: -f1 | cat -n)
-	if [ "x$elfs" = "x" ]; then
-		echo "warning: no executable ELF files found in '${git}'. Building artifacts outside the git repo? Or did you select the wrong OVE project '$ove_proj'?"
-	else
-		echo "ELF files within the '${git}' repo:"
-		printf "%s\n" "$elfs"
-	fi
+    nbr_of_probes=$(git grep 'DMCE_PROBE([0-9]\+' | grep -o 'DMCE_PROBE([0-9]\+' | cut -d'(' -f2 | sort -V | tail -1)
+    echo "info: repo '${git_full}' is now instrumented with ${nbr_of_probes} probe(s). Run some test (executable files below) and then 'ove dmce trace-decode ${git}'"
+    elfs=$(find "${git_full}" -type f -perm -u=x -print -exec file {} \;| grep ELF | cut -d: -f1 | cat -n)
+    if [ "x$elfs" = "x" ]; then
+        echo "warning: no executable ELF files found in '${git}'. Building artifacts outside the git repo? Or did you select the wrong OVE project '$ove_proj'?"
+    else
+        echo "ELF files within the '${git}' repo:"
+        printf "%s\n" "$elfs"
+    fi
 
-	exit 0
+    exit 0
 }
 
 main "$@"
