pre-push: stderr check: include fatal

diff --git a/.ove/scripts/dmce-coverage-history b/.ove/scripts/dmce-coverage-history
--- a/.ove/scripts/dmce-coverage-history
+++ b/.ove/scripts/dmce-coverage-history
@@ -362,7 +362,7 @@ function init() {
     fi
 
     if ! command -v journalctl > /dev/null; then
-        echo "error: command 'journalctl' is missing" 1>&2
+        echo "error: command 'journalctl' not found" 1>&2
         exit 1
     fi
 
diff --git a/bin/dmce b/bin/dmce
--- a/bin/dmce
+++ b/bin/dmce
@@ -1123,10 +1123,10 @@ function populate_file_list() {
 				fi
 				# sanity check and apply the diff
 				if ! git apply --check --whitespace=nowarn -- "${md5_root}/${c_file}.diff"; then
-					echo "fatal: '${md5_root}/${c_file}.diff' does not apply"
+					echo "fatal: '${md5_root}/${c_file}.diff' does not apply" 1>&2
 					exit 1
 				elif ! git apply --whitespace=nowarn -- "${md5_root}/${c_file}.diff"; then
-					echo "fatal: '${md5_root}/${c_file}.diff' does not apply"
+					echo "fatal: '${md5_root}/${c_file}.diff' does not apply" 1>&2
 					exit 1
 				fi
 
@@ -1147,7 +1147,7 @@ function populate_file_list() {
 			fi
 		elif [ -s "${state[dmce_cache_root]}/${c_file}.probedata" ]; then
 			if [ ! -s "${state[dmce_cache_root]}/${c_file}.diff" ]; then
-				echo "fatal: '${state[dmce_cache_root]}/${c_file}.diff' missing"
+				echo "fatal: '${state[dmce_cache_root]}/${c_file}.diff' not found" 1>&2
 				exit 1
 			fi
 
@@ -1749,7 +1749,7 @@ function cache_populate() {
 			fi
 		else
 			if ! git diff -- "$f" >"${dst}/${f##*/}".diff; then
-				echo "fatal: 'git diff $f' failed"
+				echo "fatal: 'git diff $f' failed" 1>&2
 				exit 1
 			fi
 		fi
diff --git a/bin/pre-push b/bin/pre-push
--- a/bin/pre-push
+++ b/bin/pre-push
@@ -5,10 +5,14 @@ set -e
 if [ ! -d .git ]; then
 	echo "error: run from git root" 1>&2
 	exit 1
-elif ! command -v shellcheck > /dev/null; then
-	echo "error: command 'shellcheck' missing" 1>&2
-	exit 1
 fi
+
+for c in shellcheck dmce alien; do
+	if ! command -v "${c}" > /dev/null; then
+		echo "error: command '${c}' not found" 1>&2
+		exit 1
+	fi
+done
 
 # for all bash shell scripts
 mapfile -t sc_list < <(\
@@ -38,6 +42,10 @@ for f in "${sc_list[@]}"; do
 		if grep 'echo "error:' "${f}" | grep -q -v '1>&2$'; then
 			echo "error: '$f': redirect errors to stderr" 1>&2
 			grep -H -n 'echo "error:' "${f}" | grep -v '1>&2$'
+			exit 1
+		elif grep 'echo "fatal:' "${f}" | grep -q -v '1>&2$'; then
+			echo "error: '$f': redirect fatal errors to stderr" 1>&2
+			grep -H -n 'echo "fatal:' "${f}" | grep -v '1>&2$'
 			exit 1
 		fi
 	fi
diff --git a/build-pkg b/build-pkg
--- a/build-pkg
+++ b/build-pkg
@@ -103,7 +103,7 @@ fi
 
 if [ "$o" = "rpm" ]; then
 	if ! command -v alien > /dev/null; then
-		echo "error: command 'alien' missing" 1>&2
+		echo "error: command 'alien' not found" 1>&2
 		exit 1
 	fi
 	o="gz"
@@ -111,10 +111,10 @@ fi
 
 if [ "$o" = "deb" ]; then
 	if ! command -v dpkg-deb > /dev/null; then
-		echo "error: command 'dpkg-deb' missing" 1>&2
+		echo "error: command 'dpkg-deb' not found" 1>&2
 		exit 1
 	elif ! command -v fakeroot > /dev/null; then
-		echo "error: command 'fakeroot' missing" 1>&2
+		echo "error: command 'fakeroot' not found" 1>&2
 		exit 1
 	fi
 	fakeroot \
